name: Scraper & Summary

#on:
#  schedule:
#    # 실제 스케쥴 작업이 시작될 cron을 등록.
#    # 크론은 https://crontab.guru/ 여기서 확인
#    # 이 크론은 일-목 22시 (한국시간 오전 7시)에 실행됩니다.
#    - cron: "00 22 * * 0-4"

on:
  workflow_dispatch:  # 수동으로 실행하는 이벤트

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run Scripts
      run: |
        python isda_scrap_main.py
    - name: Check for changes
      id: changes
      run: |
        git diff --exit-code || echo "::set-output name=changes::true"
    - name: Commits & Push
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --local user.email "ggtt7@naver.com"
        git config --local user.name "PyBack"
        git add .
        git commit -m "[Auto-Commit] daily scrap"
        git push -u origin main
#    - name: Push
#      uses: ad-m/github-push-action@master
#      with:
#        branch: 'main'
#        github_token: $